### ISSUE TITLE
Release/Deploy to PyPI via CI

### ISSUE THREAD

**Issue by mathpluscode** [DeepRegNet/DeepReg#343] opened 2020-08-26 20:19 UTC
# Issue description

It's really nice to have a detailed doc on how to release the package https://deepreg.readthedocs.io/en/latest/contributing/build.html

However, even for a developer, I think it's not necessary to know exactly how to release it.

Ideally, we should perform the deployment/release automatically using tag with the help of CI, check the docs here
https://docs.travis-ci.com/user/deployment/pypi/

So once we decide that we want to make a new release, we should just add a tag, and then it will be automatically released to the PyPI. But it is not obvious how this can be done.

## Type of Issue

- [ ] New feature request
- [ ] Documentation update

**Comment by mathpluscode** [comment] 2020-08-26 20:22
@zacbaum I found some random pages like
https://medium.com/@mikkokotila/deploying-python-packages-to-pypi-with-travis-works-9a6597781556

I think the manual upload was necessary and from now on we can switch to automated way ;)

Concerning the version and release note, we will need further discussions

**Comment by zacbaum** [comment] 2020-08-26 20:47
Definitely agree with this - why I've just left it manual for now! 😄 

The likely best option would be a `dev` branch (where all PRs are merged to) in addition to `master`. Then when we merge to `master`, we can branch and mark stable versions on GitHub and mark for release automatically and have it deploy to PyPI.

**Comment by zacbaum** [comment] 2020-08-26 21:07
Another useful way of doing it is by only tagging commits we want to make releases on...

See: https://docs.travis-ci.com/user/deployment/pypi/#deploying-tags

and see: https://github.com/73VW/Publishing-to-PyPI-with-pbr-and-Travis/blob/master/README.en.rst

**Comment by mathpluscode** [comment] 2020-08-26 21:15
@zacbaum yup yup yup, the main/dev seems to be really important now. For the tag, i totally agree, the deployment CI should be triggered by only tags, and tags can be done using GitHub web interface ;) let's see tmr

**Comment by zacbaum** [comment] 2020-09-24 12:37
Now a duplicate of #408.

**Closed by zacbaum** 2020-09-24 12:37 UTC
