### ISSUE TITLE
Add auto pypi release and update releasing guidelines

### ISSUE THREAD

**Issue by NMontanaBrown** [DeepRegNet/DeepReg#408] opened 2020-09-03 13:19 UTC
## Subject of the issue

We need to clarify release guidelines. When to release? Conventions? Write in a guide for posterity? Discuss.

**Comment by NMontanaBrown** [comment] 2020-09-03 13:19
@mathpluscode @ebonmati @MattClarkson @YipengHu @RemiDelaunay @YipengHu @QianyeYang @acasamitjana @agrimwood @zacbaum @ZheMin-1992 @s-sd

**Comment by zacbaum** [comment] 2020-09-03 13:24
When: Perhaps once per month (or longer)

Naming conventions: Per semver (Major.Minor.Batch - Major is non-backward compatible changes, minor is large changes that add new functionality, batch is fixes or small updates)

I would be in favor of manually triggered GitHub action which:
* Creates a tag
* Builds release package
* Pulls changelog (from somewhere, see #407)
* Adds release to GitHub & PyPI

Alternatively - create a tag which then:
* Triggers CI for that tagged commit
* Builds release package
* Pulls changelog (from somewhere, see #407)
* Adds release to GitHub & PyPI

**Comment by ebonmati** [comment] 2020-09-03 14:09
minor: I think is Major.Minor.Patch instead of Major.Minor.Batch

Also, once per month at which level? batch?

**Comment by zacbaum** [comment] 2020-09-03 14:11
> minor: I think is Major.Minor.Patch instead of Major.Minor.Batch

Good catch!

> Also, once per month at which level? batch?

I think this would depend on the amount of work done since the last release.

**Comment by mathpluscode** [comment] 2020-09-06 17:36
> When: Perhaps once per month (or longer)
> 
> Naming conventions: Per semver (Major.Minor.Batch - Major is non-backward compatible changes, minor is large changes that add new functionality, batch is fixes or small updates)
> 
> I would be in favor of manually triggered GitHub action which:
> 
> * Creates a tag
> * Builds release package
> * Pulls changelog (from somewhere, see #407)
> * Adds release to GitHub & PyPI
> 
> Alternatively - create a tag which then:
> 
> * Triggers CI for that tagged commit
> * Builds release package
> * Pulls changelog (from somewhere, see #407)
> * Adds release to GitHub & PyPI

Vote for github action!

**Comment by NMontanaBrown** [comment] 2020-09-07 09:51
> > When: Perhaps once per month (or longer)
> > Naming conventions: Per semver (Major.Minor.Batch - Major is non-backward compatible changes, minor is large changes that add new functionality, batch is fixes or small updates)
> > I would be in favor of manually triggered GitHub action which:
> > 
> > * Creates a tag
> > * Builds release package
> > * Pulls changelog (from somewhere, see #407)
> > * Adds release to GitHub & PyPI
> > 
> > Alternatively - create a tag which then:
> > 
> > * Triggers CI for that tagged commit
> > * Builds release package
> > * Pulls changelog (from somewhere, see #407)
> > * Adds release to GitHub & PyPI
> 
> Vote for github action!

+ 1 GitHub action

**Comment by zacbaum** [comment] 2020-09-24 12:37
#343 Closed as a duplicate of this - see there for more discussion/ideas for going about this (in an automated fashion) as well.

**Comment by mathpluscode** [comment] 2020-10-21 22:48
btw lol `DeepRegbeta will be released in Autumn 2020` we gonna enter winter...

**Comment by YipengHu** [comment] 2020-10-22 01:51
> btw lol `DeepRegbeta will be released in Autumn 2020` we gonna enter winter...

https://www.google.com/search?q=when+does+winter+start&oq=when+does+winter+start&aqs=chrome..69i57j0i402j0l6.3921j1j7&sourceid=chrome&ie=UTF-8

**Closed** 2020-11-13 21:10 UTC
Labels: docs, priority
